version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    depends_on:
      - sqldata
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "5433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
